spring.application.name=gamestop

spring.logging.level.com.gamestop=DEBUG

#
# JDBC properties
#
spring.datasource.url=jdbc:mysql://localhost:3306/gamestop
spring.datasource.username=springstudent
spring.datasource.password=springstudent
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
